name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_traffic: yes
          plugin_activity: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_followup: yes
          plugin_contributors: yes
          plugin_people: yes
          plugin_repositories: yes
          plugin_stars: yes
          plugin_stargazers: yes
          plugin_isocalendar: yes
          plugin_isocalendar_fullyear: yes
          plugin_notable: yes
          plugin_metadata: yes
